// This will handle all AI communications ... It's like "BRAIN" of our app

// Groq runs open-source models (like LLaMA by Meta) at very high speed for free
// Importing the Groq SDK
const Groq = require('groq-sdk');

// Creating a Groq client
// It automatically reads GROQ_API_KEY from your .env file
const client = new Groq();

// This is an "async function" ... it does work that takes time (like waiting for AI to respond), without freezing the whole program.
async function explainCode(code) {
    
    // We will build a "prompt" ... which will be the instruction we give to the AI
    // The better the prompt, the better the explanation!
    const prompt = `
    You are a patient coding teacher explaining code to a beginner.

    Please explain the following code in simple terms:
    - What does it do overall? (1-2 sentences)
    - Break it down section by section
    - Use simple language, no jargon
    - If you spot any interesting patterns, mention them

    Here is the code:
    \`\`\`
    ${code}
    \`\`\`
  `;

  // Send the prompt to Groq and wait for the response
  // Most AI APIs follow the same pattern ... that's intentional
  // "await" means: pause here until the AI replies, then continue
  const response = await client.chat.completions.create({
    model: 'llama-3.3-70b-versatile', // Free, powerful model by Meta
    max_tokens: 1024, // max length of the reply
    messages: [
        {
            role: 'system', // "system" sets the AI's personality/behavior
            content: 'You are a helpful coding teacher for beginners.'
        },
        {
            role: 'user', 
            // represents the user's input (the actual prompt/question)
            content: prompt
        }
    ]
  });

  // The response is a structured object, not plain text
  // Groq returns results inside a "choices" array

  return response.choices[0].message.content;
  // Step-by-step extraction:
  // 1. response.choices → list of possible AI replies
  // 2. [0] → take the first (main) reply
  // 3. .message → the actual message object
  // 4. .content → the text generated by the AI
}

// "module.exports" is used to make the function public so that it can be accessed by other files
module.exports = { explainCode };